[CmdletBinding()]
param(
    [ValidateSet('BoundedAutonomy', 'AskMe', 'AutoReview')][string]$ApprovalMode = 'BoundedAutonomy',
    [ValidateSet('Off', 'Allowlist', 'Unrestricted')][string]$NetworkMode = 'Off',
    [string[]]$AllowedDomain = @(),
    [ValidateSet('Elevated', 'Unelevated', 'Keep')][string]$WindowsSandbox = 'Elevated',
    [bool]$ProtectWorkspaceSecrets = $true,
    [bool]$AllowTempWrite = $false,
    [string]$WorkspacePath,
    [string]$CodexHome,
    [string]$ConfigPath,
    [string]$StateRoot,
    [switch]$MigrateLegacySettings,
    [switch]$AcknowledgeRisk,
    [switch]$AcknowledgeAdminSetup,
    [switch]$PlanOnly,
    [switch]$ConfirmApply,
    [switch]$NonInteractive
)

. (Join-Path $PSScriptRoot 'Common.ps1')
$ErrorActionPreference = 'Stop'

$resolvedHome = Get-CssCodexHome -Override $CodexHome
$resolvedConfig = Get-CssConfigPath -CodexHome $resolvedHome -Override $ConfigPath
$resolvedState = Get-CssStateRoot -CodexHome $resolvedHome -Override $StateRoot
$filesystemRoot = [IO.Path]::GetPathRoot($resolvedHome)
$pathTrimCharacters = [char[]]@([IO.Path]::DirectorySeparatorChar, [IO.Path]::AltDirectorySeparatorChar)
$pathComparison = if ($env:OS -eq 'Windows_NT') { [StringComparison]::OrdinalIgnoreCase } else { [StringComparison]::Ordinal }
if ([string]::Equals($resolvedHome.TrimEnd($pathTrimCharacters), $filesystemRoot.TrimEnd($pathTrimCharacters), $pathComparison)) {
    throw "Refusing to use a filesystem root as CodexHome: $resolvedHome"
}
$expectedConfig = [IO.Path]::GetFullPath((Join-Path $resolvedHome 'config.toml'))
$expectedState = [IO.Path]::GetFullPath((Join-Path $resolvedHome 'safe-setup'))
if (-not [string]::Equals($resolvedConfig, $expectedConfig, $pathComparison)) {
    throw "ConfigPath must resolve to the config.toml directly under CodexHome: $expectedConfig"
}
if (-not [string]::Equals($resolvedState, $expectedState, $pathComparison)) {
    throw "StateRoot must resolve to the safe-setup directory directly under CodexHome: $expectedState"
}
$existingConfig = Read-CssText -Path $resolvedConfig
$legacy = Test-CssLegacySettings -Text $existingConfig

$codexCommandForVersion = Get-Command codex -ErrorAction SilentlyContinue | Select-Object -First 1
if ($codexCommandForVersion) {
    $codexVersionText = (& $codexCommandForVersion.Source --version 2>$null | Select-Object -First 1)
    if ($codexVersionText -and $codexVersionText.ToString() -match '(\d+\.\d+\.\d+)' -and [version]$Matches[1] -lt [version]'0.138.0') {
        throw "Codex CLI $($Matches[1]) is too old for the managed permission-profile format. Update Codex or use a compatible installer version."
    }
}

if ($legacy.Present -and -not $MigrateLegacySettings) {
    throw 'Legacy sandbox settings are present. Review the plan and rerun with -MigrateLegacySettings to replace the conflicting keys with a backed-up permission profile.'
}
if ($NetworkMode -eq 'Allowlist' -and $AllowedDomain.Count -eq 0) {
    throw 'Allowlist mode requires at least one -AllowedDomain.'
}
foreach ($domain in $AllowedDomain) {
    if ($domain -notmatch '^(\*\*?\.)?([A-Za-z0-9-]+\.)*[A-Za-z0-9-]+$') {
        throw "Invalid domain pattern '$domain'. Use a hostname or a leading *. / **. wildcard without a scheme, port, path, or quotes."
    }
}

$approvalPolicy = 'never'
$approvalReviewer = 'user'
if ($ApprovalMode -eq 'AskMe') { $approvalPolicy = 'on-request' }
if ($ApprovalMode -eq 'AutoReview') { $approvalPolicy = 'on-request'; $approvalReviewer = 'auto_review' }

$newConfig = Remove-CssManagedBlock -Text $existingConfig
if ($MigrateLegacySettings) {
    $newConfig = Remove-CssTomlTopLevelKeys -Text $newConfig -Keys @('sandbox_mode')
    $newConfig = Remove-CssTomlSections -Text $newConfig -SectionPrefixes @('sandbox_workspace_write')
}
$newConfig = Remove-CssTomlSections -Text $newConfig -SectionPrefixes @("permissions.$($script:CssProfileName)")
$newConfig = Set-CssTomlTopLevelValue -Text $newConfig -Key 'default_permissions' -Literal (ConvertTo-CssTomlString $script:CssProfileName)
$newConfig = Set-CssTomlTopLevelValue -Text $newConfig -Key 'approval_policy' -Literal (ConvertTo-CssTomlString $approvalPolicy)
$newConfig = Set-CssTomlTopLevelValue -Text $newConfig -Key 'approvals_reviewer' -Literal (ConvertTo-CssTomlString $approvalReviewer)

if ($NetworkMode -ne 'Off') {
    $newConfig = Set-CssTomlSectionValue -Text $newConfig -Section 'features' -Key 'network_proxy' -Literal 'true'
}
if ($WindowsSandbox -ne 'Keep' -and $env:OS -eq 'Windows_NT') {
    $sandboxLiteral = if ($WindowsSandbox -eq 'Elevated') { 'elevated' } else { 'unelevated' }
    $newConfig = Set-CssTomlSectionValue -Text $newConfig -Section 'windows' -Key 'sandbox' -Literal (ConvertTo-CssTomlString $sandboxLiteral)
}

$managedLines = [Collections.Generic.List[string]]::new()
$managedLines.Add($script:CssManagedStart)
$managedLines.Add('# Generated by Install-CodexSafety.ps1. Re-run the installer instead of editing this block.')
$managedLines.Add("[permissions.$($script:CssProfileName)]")
$managedLines.Add('extends = ":workspace"')
$managedLines.Add('')
$managedLines.Add("[permissions.$($script:CssProfileName).filesystem]")
$managedLines.Add('":root" = "deny"')
$managedLines.Add('":minimal" = "read"')
if (-not $AllowTempWrite) {
    $managedLines.Add('":tmpdir" = "deny"')
    $managedLines.Add('":slash_tmp" = "deny"')
}
if ($ProtectWorkspaceSecrets) { $managedLines.Add('glob_scan_max_depth = 6') }
$managedLines.Add('')
$managedLines.Add(('[permissions.{0}.filesystem.":workspace_roots"]' -f $script:CssProfileName))
$managedLines.Add('"." = "write"')
if ($ProtectWorkspaceSecrets) {
    foreach ($pattern in @('.env', '.env.*', '**/.env', '**/.env.*', '**/.npmrc', '**/.pypirc', '**/.netrc', '**/credentials.json', '**/service-account.json', '**/*.pem', '**/*.key', '**/*.pfx', '**/*.p12')) {
        $managedLines.Add((ConvertTo-CssTomlString $pattern) + ' = "deny"')
    }
}
$managedLines.Add('')
$managedLines.Add("[permissions.$($script:CssProfileName).network]")
$managedLines.Add('enabled = ' + $(if ($NetworkMode -eq 'Off') { 'false' } else { 'true' }))
if ($NetworkMode -eq 'Allowlist' -or $NetworkMode -eq 'Unrestricted') {
    $managedLines.Add('')
    $managedLines.Add("[permissions.$($script:CssProfileName).network.domains]")
    if ($NetworkMode -eq 'Unrestricted') {
        $managedLines.Add('"*" = "allow"')
    }
    else {
        foreach ($domain in ($AllowedDomain | Sort-Object -Unique)) {
            $managedLines.Add((ConvertTo-CssTomlString $domain) + ' = "allow"')
        }
    }
}
$managedLines.Add($script:CssManagedEnd)
$managedBlock = $managedLines -join [Environment]::NewLine
$newConfig = $newConfig.TrimEnd() + [Environment]::NewLine + [Environment]::NewLine + $managedBlock + [Environment]::NewLine

$resolvedWorkspace = $null
if ($WorkspacePath) {
    $gitCommandForBridge = Get-Command git -ErrorAction SilentlyContinue | Select-Object -First 1
    if (-not $gitCommandForBridge) { throw 'Git is required to register a checkpoint workspace.' }
    $resolvedWorkspace = Get-CssRepositoryRoot -Path $WorkspacePath
    $gitExecutableForBridge = [IO.Path]::GetFullPath($gitCommandForBridge.Source)
    $gitExecutableHash = (Get-FileHash -LiteralPath $gitExecutableForBridge -Algorithm SHA256).Hash
}

$plan = [pscustomobject]@{
    ConfigPath = $resolvedConfig
    StateRoot = $resolvedState
    ApprovalMode = $ApprovalMode
    ApprovalPolicy = $approvalPolicy
    ApprovalReviewer = $approvalReviewer
    NetworkMode = $NetworkMode
    AllowedDomains = $AllowedDomain
    Filesystem = 'deny root; read minimal runtime; write workspace roots'
    ProtectWorkspaceSecrets = $ProtectWorkspaceSecrets
    AllowTempWrite = $AllowTempWrite
    WindowsSandbox = $WindowsSandbox
    MigrateLegacySettings = [bool]$MigrateLegacySettings
    RegisteredWorkspace = $resolvedWorkspace
    CheckpointBridge = $(if ($resolvedWorkspace) { 'Install when PowerShell 7 is available' } else { 'Not requested' })
    ExternalSurfaces = 'Web Search, Browser, Computer Use, apps, plugins, MCP, and cloud tasks are not controlled.'
}

Write-Output 'Codex Safe Setup - change plan'
$plan | Format-List | Out-String | Write-Output
if ($PlanOnly) {
    Write-Output 'No files changed (PlanOnly).'
    return
}

if ($NetworkMode -eq 'Unrestricted' -and -not $AcknowledgeRisk) {
    if ($NonInteractive) { throw 'Unrestricted command networking requires -AcknowledgeRisk.' }
    $riskAnswer = Read-Host 'Unrestricted public outbound access can exfiltrate code or secrets. Continue? [y/N]'
    if ($riskAnswer -notmatch '^(?i:y|yes)$') { throw 'Installation cancelled.' }
}
if ($WindowsSandbox -eq 'Elevated' -and $env:OS -eq 'Windows_NT' -and -not $AcknowledgeAdminSetup) {
    if ($NonInteractive) { throw 'Elevated Windows sandbox selection requires -AcknowledgeAdminSetup.' }
    $adminAnswer = Read-Host 'The elevated Windows sandbox may require an administrator-approved setup prompt. Continue? [y/N]'
    if ($adminAnswer -notmatch '^(?i:y|yes)$') { throw 'Installation cancelled.' }
}
if (-not $ConfirmApply) {
    if ($NonInteractive) { throw 'Non-interactive application requires -ConfirmApply.' }
    $applyAnswer = Read-Host 'Apply this exact plan and create a rollback backup? [y/N]'
    if ($applyAnswer -notmatch '^(?i:y|yes)$') { throw 'Installation cancelled.' }
}

$timestamp = [DateTime]::UtcNow.ToString('yyyyMMddTHHmmssfffZ')
$backupRoot = Join-Path $resolvedState 'backups'
$binaryRoot = Join-Path $resolvedState 'bin'
$rulesRoot = Join-Path $resolvedHome 'rules'
$rulesPath = Join-Path $rulesRoot 'codex-safe-setup.rules'
$bridgePath = Join-Path $binaryRoot 'New-CodexCheckpoint.ps1'
$authorizedPath = Join-Path $resolvedState 'authorized-workspaces.json'
$canaryPath = Join-Path $resolvedState 'outside-workspace-canary.txt'
$configBackup = Join-Path $backupRoot ("config.$timestamp.toml")
$rulesBackup = Join-Path $backupRoot ("rules.$timestamp.bak")
$bridgeBackup = Join-Path $backupRoot ("bridge.$timestamp.bak")
$authorizedBackup = Join-Path $backupRoot ("authorized-workspaces.$timestamp.bak")
$canaryBackup = Join-Path $backupRoot ("canary.$timestamp.bak")
$originalConfigExists = Test-Path -LiteralPath $resolvedConfig -PathType Leaf
$originalRulesExists = Test-Path -LiteralPath $rulesPath -PathType Leaf
$originalBridgeExists = Test-Path -LiteralPath $bridgePath -PathType Leaf
$originalAuthorizedExists = Test-Path -LiteralPath $authorizedPath -PathType Leaf
$originalCanaryExists = Test-Path -LiteralPath $canaryPath -PathType Leaf

New-Item -ItemType Directory -Path $backupRoot -Force | Out-Null
New-Item -ItemType Directory -Path $binaryRoot -Force | Out-Null
New-Item -ItemType Directory -Path $rulesRoot -Force | Out-Null
if ($originalConfigExists) { Copy-Item -LiteralPath $resolvedConfig -Destination $configBackup -Force }
if ($originalRulesExists) { Copy-Item -LiteralPath $rulesPath -Destination $rulesBackup -Force }
if ($originalBridgeExists) { Copy-Item -LiteralPath $bridgePath -Destination $bridgeBackup -Force }
if ($originalAuthorizedExists) { Copy-Item -LiteralPath $authorizedPath -Destination $authorizedBackup -Force }
if ($originalCanaryExists) { Copy-Item -LiteralPath $canaryPath -Destination $canaryBackup -Force }

$bridgeInstalled = $false
$ruleInstalled = $false
$authorizedTouched = [bool]$resolvedWorkspace
$canaryTouched = $true
try {
    Write-CssTextAtomic -Path $resolvedConfig -Text $newConfig
    Write-CssTextAtomic -Path $canaryPath -Text ("Synthetic canary only: {0}" -f [guid]::NewGuid().ToString('N'))

    if ($resolvedWorkspace) {
        $authorizedRoots = @()
        if (Test-Path -LiteralPath $authorizedPath -PathType Leaf) {
            try { $authorizedRoots = @((Get-Content -LiteralPath $authorizedPath -Raw | ConvertFrom-Json).roots) } catch { $authorizedRoots = @() }
        }
        $authorizedRoots = @($authorizedRoots + $resolvedWorkspace | Where-Object { $_ } | Sort-Object -Unique)
        $bridgeRegistry = [pscustomobject]@{
            schemaVersion = 1
            gitExecutable = $gitExecutableForBridge
            gitExecutableSha256 = $gitExecutableHash
            roots = $authorizedRoots
        }
        Write-CssTextAtomic -Path $authorizedPath -Text ($bridgeRegistry | ConvertTo-Json -Depth 3)

        $pwshCommand = Get-Command pwsh -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($pwshCommand) {
            $bridgeInstalled = $true
            Copy-Item -LiteralPath (Join-Path $PSScriptRoot 'New-CodexCheckpoint.ps1') -Destination $bridgePath -Force
            $pwshRulePath = [IO.Path]::GetFullPath($pwshCommand.Source)
            $scriptRulePath = [IO.Path]::GetFullPath($bridgePath)
            $workspaceRulePath = [IO.Path]::GetFullPath($resolvedWorkspace)
            $pwshLiteral = ConvertTo-CssStarlarkString -Value $pwshRulePath
            $scriptLiteral = ConvertTo-CssStarlarkString -Value $scriptRulePath
            $saveExample = ConvertTo-CssStarlarkString -Value ('"{0}" -NoProfile -NonInteractive -File "{1}" -Action Save -Repository "{2}"' -f $pwshRulePath, $scriptRulePath, $workspaceRulePath)
            $listExample = ConvertTo-CssStarlarkString -Value ('"{0}" -NoProfile -NonInteractive -File "{1}" -Action List -Repository "{2}"' -f $pwshRulePath, $scriptRulePath, $workspaceRulePath)
            $unsafeExample = ConvertTo-CssStarlarkString -Value ('"{0}" -NoProfile -File "{1}" -Action Save -Repository "{2}"' -f $pwshRulePath, $scriptRulePath, $workspaceRulePath)
            $ruleText = @"
# Generated by Codex Safe Setup. Exact bridge only; never general PowerShell or Git.
prefix_rule(
    pattern = [$pwshLiteral, "-NoProfile", "-NonInteractive", "-File", $scriptLiteral, "-Action", ["Save", "List"]],
    decision = "allow",
    justification = "Create or list a checkpoint only in a user-registered repository",
    match = [
        $saveExample,
        $listExample,
    ],
    not_match = [
        $unsafeExample,
        'git commit',
    ],
)
"@
            $ruleInstalled = $true
            Write-CssTextAtomic -Path $rulesPath -Text $ruleText
        }
    }

    $state = [pscustomobject]@{
        InstalledAtUtc = [DateTime]::UtcNow.ToString('o')
        ConfigPath = $resolvedConfig
        OriginalConfigExists = $originalConfigExists
        ConfigBackup = $(if ($originalConfigExists) { $configBackup } else { $null })
        RulesPath = $rulesPath
        OriginalRulesExists = $originalRulesExists
        RulesBackup = $(if ($originalRulesExists) { $rulesBackup } else { $null })
        RulesTouched = $ruleInstalled
        BridgePath = $(if ($bridgeInstalled) { $bridgePath } else { $null })
        OriginalBridgeExists = $originalBridgeExists
        BridgeBackup = $(if ($originalBridgeExists) { $bridgeBackup } else { $null })
        BridgeTouched = $bridgeInstalled
        AuthorizedWorkspacesPath = $authorizedPath
        OriginalAuthorizedWorkspacesExists = $originalAuthorizedExists
        AuthorizedWorkspacesBackup = $(if ($originalAuthorizedExists) { $authorizedBackup } else { $null })
        AuthorizedWorkspacesTouched = $authorizedTouched
        CanaryPath = $canaryPath
        OriginalCanaryExists = $originalCanaryExists
        CanaryBackup = $(if ($originalCanaryExists) { $canaryBackup } else { $null })
        CanaryTouched = $canaryTouched
        ApprovalMode = $ApprovalMode
        NetworkMode = $NetworkMode
        WindowsSandbox = $WindowsSandbox
        RegisteredWorkspace = $resolvedWorkspace
    }
    Write-CssTextAtomic -Path (Join-Path $resolvedState 'install-state.json') -Text ($state | ConvertTo-Json -Depth 5)
}
catch {
    if ($originalConfigExists) { Copy-Item -LiteralPath $configBackup -Destination $resolvedConfig -Force }
    elseif (Test-Path -LiteralPath $resolvedConfig) { Remove-Item -LiteralPath $resolvedConfig -Force }
    if ($originalRulesExists) { Copy-Item -LiteralPath $rulesBackup -Destination $rulesPath -Force }
    elseif (Test-Path -LiteralPath $rulesPath) { Remove-Item -LiteralPath $rulesPath -Force }
    if ($bridgeInstalled) {
        if ($originalBridgeExists) { Copy-Item -LiteralPath $bridgeBackup -Destination $bridgePath -Force }
        elseif (Test-Path -LiteralPath $bridgePath) { Remove-Item -LiteralPath $bridgePath -Force }
    }
    if ($authorizedTouched) {
        if ($originalAuthorizedExists) { Copy-Item -LiteralPath $authorizedBackup -Destination $authorizedPath -Force }
        elseif (Test-Path -LiteralPath $authorizedPath) { Remove-Item -LiteralPath $authorizedPath -Force }
    }
    if ($canaryTouched) {
        if ($originalCanaryExists) { Copy-Item -LiteralPath $canaryBackup -Destination $canaryPath -Force }
        elseif (Test-Path -LiteralPath $canaryPath) { Remove-Item -LiteralPath $canaryPath -Force }
    }
    throw
}

[pscustomobject]@{
    Status = 'INSTALLED_RESTART_REQUIRED'
    ConfigPath = $resolvedConfig
    BackupPath = $(if ($originalConfigExists) { $configBackup } else { '<new config; rollback removes it>' })
    CheckpointBridgeInstalled = $bridgeInstalled
    RuleInstalled = $ruleInstalled
    Verification = $(if (Get-Command codex -ErrorAction SilentlyContinue) { 'Run Test-CodexSafety.ps1 after restarting Codex.' } else { 'PARTIAL: install Codex CLI for rule verification.' })
}
